[[accounts]]
email = "idyllic4202@wplacetools.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "espialeilani+grace@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "ar.r.o.g.anc.e.p.c.hz.xp@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "theobald2798+gladden@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "vj.zh.z.h.d.b.b.d.udhj.db@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[deepseek]
api_base = "https://chat.deepseek.com/api/v0"
wasm_url = "https://fe-static.deepseek.com/chat/static/sha3_wasm_bg.7b9ca65ddd.wasm"
user_agent = "DeepSeek/2.0.4 Android/35"
client_version = "2.0.4"
client_platform = "android"
client_locale = "en_US"
model_types = [
    "default",
    "expert",
    "reasoner",
]
max_input_tokens = [
    1048576,
    1048576,
    1048576,
]
max_output_tokens = [
    384000,
    384000,
    384000,
]
model_aliases = [
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "deepseek-r1",
]

[deepseek.tool_call]
extra_starts = [
    "<|tool_call_begin|>",
    "<tool_calls>",
    "<tool_call>",
]
extra_ends = [
    "<|tool_call_end|>",
    "</tool_calls>",
    "</tool_call>",
]

[server]
host = "127.0.0.1"
port = 22217
cors_origins = ["*"]

[proxy]

[admin]
password_hash = "$2b$12$g02zDcR3rzUTa9qdhJlpNuhM6TImSleIO6A/NCyBHR9uXD3y7ME7O"
jwt_secret = "5ed79705acad1652c1f7abbc705f264f7ea6286a18c2261fcb11fb00c01ba4a1"
jwt_issued_at = 1785074314

[[api_keys]]
key = "sk-zoya-test-key-2026"
description = "ZOYA Test Key"
